name: 'apple_search_ads_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]


vars:
  apple_search_ads_source:
    organization: "{{ source('apple_search_ads', 'organization') }}"
    campaign_history: "{{ source('apple_search_ads', 'campaign_history') }}"
    campaign_report: "{{ source('apple_search_ads', 'campaign_report') }}"
    ad_group_history: "{{ source('apple_search_ads', 'ad_group_history') }}"
    ad_group_report: "{{ source('apple_search_ads', 'ad_group_report') }}"
    keyword_history: "{{ source('apple_search_ads', 'keyword_history') }}"
    keyword_report: "{{ source('apple_search_ads', 'keyword_report') }}"
    search_term_report: "{{ source('apple_search_ads', 'search_term_report') }}"
    apple_search_ads__using_search_terms: true

models:
  apple_search_ads_source:
    materialized: table
    +schema: stg_apple_search_ads
    tmp:
      materialized: view
